In [3]:
import numpy as np

In [4]:
# https://www.runoob.com/numpy/numpy-dtype.html
# 将数据类型应用于 ndarray 对象
# dtype
datatype = np.dtype([('age', np.int8)])
a = np.array([(10, ), (20, ), (30, )], dtype=datatype)
print(a)
print(a['age'])
print('==========================================================================')

datatype = np.dtype([('age', np.int8), ('name', 'S20'), ('marks', np.float32)])
student = np.array([(20, 'zgq', 100.00), (21, 'yzy', 99.00), (22, 'wjy', 99.99)], dtype=datatype)
print(student)
print(student.dtype)
print(student['age'], student['age'].dtype)
print(student['name'], student['name'].dtype)
print(student['marks'], student['marks'].dtype)

[(10,) (20,) (30,)]
[10 20 30]
[(20, b'zgq',  100.        ) (21, b'yzy',   99.        )
 (22, b'wjy',   99.98999786)]
[('age', 'i1'), ('name', 'S20'), ('marks', '<f4')]
[20 21 22] int8
[b'zgq' b'yzy' b'wjy'] |S20
[ 100.           99.           99.98999786] float32


In [5]:
# 数组属性 https://www.runoob.com/numpy/numpy-array-attributes.html
# size
# shape
# itemsize
# flags
a = np.arange(24)
print(a)
print('==========================================================================')
print('a.size', a.size)  # size属性是数组的总大小，不会随着形状改变而变化
print('a.shape', a.shape)  # shape是数值的形状，数组形状变化，该值也会变化，返回数组
a.resize(2, 4, 3)
print(a)
print('a.shape.after', a.shape)
print('a.size.after', a.size)
print('==========================================================================')
a.shape = (2, 12)
print(a)
print('==========================================================================')
print('a.itemsize', a.itemsize)  # itemsize返回一个值在内存中存储所在空间，int占用4个字节，float64占用8个字节
a = np.arange(1, dtype=np.float64)
print('a.itemsize.after', a.itemsize)
print('a.flag:\n', a.flags)  # flag属性是数组相应的内存信息

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
a.size 24
a.shape (24,)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
a.shape.after (2, 4, 3)
a.size.after 24
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
a.itemsize 4
a.itemsize.after 8
a.flag:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [6]:
# Numpy创建数组 https://www.runoob.com/numpy/numpy-array-creation.html
# empty
# ones
# zeros
x = np.empty((2, 4), dtype=np.float32)
print(x)
print('========================================================')
y = np.zeros((4, ), dtype=np.float32)
print(y)
print('========================================================')
z = np.ones((2, 2), dtype=[('first', np.int), ('second', np.float)])
print(z)

[[ -9.14230189e-17   5.94150549e-43   4.26545519e-08   1.71829757e-04]
 [  1.99712970e+20   1.30864625e-11   1.06166408e+21   4.22777920e+21]]
[ 0.  0.  0.  0.]
[[(1,  1.) (1,  1.)]
 [(1,  1.) (1,  1.)]]


In [7]:
# NumPy 从已有的数组创建数组 https://www.runoob.com/numpy/numpy-array-from-existing-data.html
# asarray
# frombuffer
# fromiter
a = [1, 2, 3]   # list
data_a = np.asarray(a, dtype=np.float)
print(data_a)
print('========================================================')
b = (4, 5, 6)  # tuple
data_b = np.asarray(b, dtype=np.int)
print(data_b)
print('========================================================')
c = [(1, 2, 3), (4, 5)]   # 当列数不同时，是一维数组
data_c = np.asarray(c)
print(data_c)
print('========================================================')
d = [(1, 2, 3), (4, 5, 6)]  # 当列数相同时，变为二维数组
data_d = np.asarray(d)
print(data_d)
print('========================================================')
e = b'Hello'  # Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b
data_e = np.frombuffer(e, dtype='S1')
print(data_e)
print('========================================================')
f = range(10)
it = iter(f)
data_f = np.fromiter(it, dtype=float)
print(data_f)

[ 1.  2.  3.]
[4 5 6]
[(1, 2, 3) (4, 5)]
[[1 2 3]
 [4 5 6]]
[b'H' b'e' b'l' b'l' b'o']
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [8]:
# 从数值范围创建数组 https://www.runoob.com/numpy/numpy-array-from-numerical-ranges.html
# np.arange(start = 0, stop, step, dtype)
# np.linespace(start, stop, num, endpoint=True, retstep, dtype)  等差数列
# np.logspace(start, stop, num, endpoint=True, base, dtype)      等比数列
# start 开始值，默认为0
# stop 结束值
# num 取点数量
# endpoint 是否包含stop的值，默认为TRUE
# retstep 如果为 True 时，生成的数组中会显示间距，反之不显示
# base 对数 log 的底数
a = np.arange(10, dtype=np.float) # 10位stop，start默认为0
print(a)
print('=================================================================================================')
b = np.arange(1, 10, 2, dtype=int) # 不包括stop值
print(b)
print('=================================================================================================')
c = np.linspace(1, 10, 10) # 默认包括stop值
print(c)
print('=================================================================================================')
d = np.linspace(1, 10, 10, endpoint=False, retstep=True) # 设置不包括stop值，并显示距离
print(d)
print('=================================================================================================')
e = np.logspace(1, 2, 10)
print(e)
print('=================================================================================================')
f = np.logspace(1, 2, 6, base=2).reshape(3, 2)
print(f)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[1 3 5 7 9]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
(array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1]), 0.90000000000000002)
[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]
[[ 2.          2.29739671]
 [ 2.63901582  3.03143313]
 [ 3.48220225  4.        ]]


In [9]:
# 切片和索引 https://www.runoob.com/numpy/numpy-indexing-and-slicing.html
# slice(start, stop, step)
# [start : stop : step]
# [2] 直接返回对应位置的元素
# [2:] 返回从2到最后元素
# [2:7] 返回从2到7（不包括7）的元素
# [..., 1] 表示包含全部行，获取第2列
# [1, ...] 表示包含全部列，获取第2行
a = np.arange(10)
print(a)
print('=================================================================================================')
s = slice(2, 8, 2)
print(a[s])
print('=================================================================================================')
print('a[2]\t', a[2])
print('a[2:]\t', a[2:])
print('a[2:8]\t', a[2:8])
print('a[2:8:2]\t', a[2:8:2])
print('=================================================================================================')
b = np.arange(9).reshape(3, 3)
print(b)
print('=================================================================================================')
print('b[1:]为\n', b[1:])
print('b[..., 1]为\n', b[..., 1])  # ... 如果在行位置使用省略号，它将返回包含行中元素的 ndarray
print('b[1, ...]为\n', b[1, ...])
print('b[..., 1:]为\n', b[..., 1:])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
a[2]	 2
a[2:]	 [2 3 4 5 6 7 8 9]
a[2:8]	 [2 3 4 5 6 7]
a[2:8:2]	 [2 4 6]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
b[1:]为
 [[3 4 5]
 [6 7 8]]
b[..., 1]为
 [1 4 7]
b[1, ...]为
 [3 4 5]
b[..., 1:]为
 [[1 2]
 [4 5]
 [7 8]]


In [10]:
# 高级索引 https://www.runoob.com/numpy/numpy-advanced-indexing.html
# 整数数组索引
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print('获取[0, 0], [1, 1], [2, 0]位置的值\t', a[[0, 1, 2], [0, 1, 0]]) # 索引结果是一维的
print('============================================================================================')
a = np.arange(1, 13).reshape(4, 3)
print(a)
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
print('行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]\n', a[rows, cols])  # 索引结果是二维的
print('等同于：')
print(a[
    [[0, 0], [3, 3]],
    [[0, 2], [0, 2]]
])
print('============================================================================================')
a = np.arange(1, 10).reshape(3, 3)
print(a)
print('a[1:3, 1:3]为\n', a[1:3, 1:3])
print('a[1:3, [1, 2]]为\n', a[1:3, [1, 2]])
print('a[..., 1:]为\n', a[..., 1:])
print('============================================================================================')

# 布尔索引:通过一个布尔数组来索引目标数组
x = np.arange(0, 12).reshape(4, 3)
print('x[x>5]为：\n', x[x>5])                     # 输出结构是一维的
print('============================================================================================')
x = np.array([np.nan, 1, 2, 3, np.nan, 4, 5])
print('~np.isnan(x):\n', x[~np.isnan(x)])        # np.isnan获取为nan的位置，然后取补运算符得到非Nan的
print('============================================================================================')
x = np.array([[1, 2 + 6j], [2, 3 + 6j]])
print(x)
print('np.iscomplex(x):\n', x[np.iscomplex(x)])  # 从数组中过滤掉非复数元素
print('============================================================================================')

# 花式索引:利用整数数组进行索引,花式索引跟切片不一样，它总是将数据**复制**到新数组中
x = np.arange(32).reshape(8, 4)
print(x)
print('x[[4, 2, 1, 7]]:\n', x[[4, 2, 1, 7]])
print('x[[-4, -2, -1, -7]]:\n', x[[-4, -2, -1, -7]])
print('x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]:\n', x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]) #np.ix_产生笛卡尔积,(1,0), (1, 3), (1, 1), (1, 2)...(2, 2)
print('上式等价于：x[[1, 5, 7, 2]][:, 0, 3, 1, 2]:\n', x[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[1 2]
 [3 4]
 [5 6]]
获取[0, 0], [1, 1], [2, 0]位置的值	 [1 4 5]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]
 [[ 1  3]
 [10 12]]
等同于：
[[ 1  3]
 [10 12]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
a[1:3, 1:3]为
 [[5 6]
 [8 9]]
a[1:3, [1, 2]]为
 [[5 6]
 [8 9]]
a[..., 1:]为
 [[2 3]
 [5 6]
 [8 9]]
x[x>5]为：
 [ 6  7  8  9 10 11]
~np.isnan(x):
 [ 1.  2.  3.  4.  5.]
[[ 1.+0.j  2.+6.j]
 [ 2.+0.j  3.+6.j]]
np.iscomplex(x):
 [ 2.+6.j  3.+6.j]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
x[[4, 2, 1, 7]]:
 [[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
x[[-4, -2, -1, -7]]:
 [[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]
x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]:
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
上式等价于：x[[1, 5, 7, 2]][:, 0, 3, 1, 2]:
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [11]:
# NumPy 广播(Broadcast) https://www.runoob.com/numpy/numpy-broadcast.html
# a.shape ==  b.shape， 对应为相乘
# a.shape != b.shape, 启动广播机制， 图解：https://www.cnblogs.com/jiaxin359/p/9021726.html
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print('a * b = ', a * b)
print('============================================================================================')
a = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30 ,30]
])
b = np.array([1, 2, 3]) # 沿着相同的维度进行broadcasting
print(a + b)
print('============================================================================================')
b_ = np.tile(b, (4, 1)) # 解释：https://www.jianshu.com/p/9519f1984c70
print(b_)
print(a + b_)

a * b =  [10 40 90]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [12]:
# NumPy 迭代数组 https://www.runoob.com/numpy/numpy-terating-over-array.html
# NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。迭代器最基本的任务的可以完成对数组元素的访问。
a = np.arange(6).reshape(2, 3)
print(a)
for x in np.nditer(a):
    print(x, end = '，')
print('\n============================================================================================')

# 控制遍历顺序
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
print(a.T)
b1 = a.T.copy(order='C')  # C order，即是行序优先
for x in np.nditer(b1):
    print(x, end=',')
print('\n')
b2 = a.T.copy(order='F')  # Fortran order，即是列序优先
for x in np.nditer(b2):
    print(x, end=',')
print('\n============================================================================================')

# 可以通过显式设置，来强制 nditer 对象使用某种顺序：
print(a)
for x in np.nditer(a, order='C'):
    print(x, end=',')
print('\n')
for x in np.nditer(a, order='F'):
    print(x, end=',')
print('\n============================================================================================')

# 修改数组中元素的值
# 设置op_flags, 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only）
# 为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式
print(a)
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 2 * x
print('After rewrite:\n', a)
print('\n============================================================================================')

# 使用外部循环
# c_index 可以跟踪 C 顺序的索引
# f_index 可以跟踪 Fortran 顺序的索引
# multi-index 每次迭代可以跟踪一种索引类型
# external_loop 给出的值是具有多个值的一维数组，而不是零维数组
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x, end=',')
print('\n============================================================================================')

# 广播迭代：如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。
a = np.arange(0, 60, 5).reshape(3, 4)
print(a)
b = np.array([1, 2, 3, 4], dtype=int)
print(b)
for x, y in np.nditer([a, b]):
    print('%d:%d' % (x, y), end=',')


[[0 1 2]
 [3 4 5]]
0，1，2，3，4，5，
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0,20,40,5,25,45,10,30,50,15,35,55,

0,5,10,15,20,25,30,35,40,45,50,55,
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0,5,10,15,20,25,30,35,40,45,50,55,

0,20,40,5,25,45,10,30,50,15,35,55,
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
After rewrite:
 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0 20 40],[ 5 25 45],[10 30 50],[15 35 55],
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]
0:1,5:2,10:3,15:4,20:1,25:2,30:3,35:4,40:1,45:2,50:3,55:4,

In [13]:
# Numpy 数组操作 https://www.runoob.com/numpy/numpy-array-manipulation.html
# 修改数组形状 reshape, flat, flatten, ravel
# 翻转数组 transpose, ndaary.T, rollaxis, swapaxes
# 修改数组维度 broadcast, broadcast_to, expand_dim, squeeze
# 连接数组 concatente, stack, hstack, vstack
# 分割数组 split, hsplit, vsplit
# 数组元素的添加与删除 resize, append, insert, delete, unique

# reshape
a = np.arange(8).reshape(4, 2)
print(a)
print('\n============================================================================================')

# flat 对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器
a = np.arange(9).reshape(3, 3)
print(a)
for row in a:
    print(row)
for element in a.flat:  
    print(element)
print('\n============================================================================================')
 
# flatten  返回一份数组拷贝，对拷贝所做的修改不会影响原始数组
a = np.arange(8).reshape(2, 4)
print(a)
print('a.flatten展开:', a.flatten())
print('a.flatten以F顺序展开：', a.flatten(order='F'))
b = a.flatten()
b[0] = -1
print('返回的是拷贝，所以不会改变原始数组:\n', a)
print('\n============================================================================================')

# ravel  展平的数组元素，顺序通常是"C风格"，返回的是数组视图(类似C中的引用）, 修改会影响原始数组。
a = np.arange(8).reshape(2, 4)
print(a)
print('a.reval展开，默认C顺序：', a.ravel())
print('a.reval以F顺序展开：', a.ravel(order='F'))
b = a.ravel()
b[0] = -1
print('返回的是视图，所以会导致原始数组改变:\n', a)
print('\n============================================================================================')

# transpose 函数用于对换数组的维度
a = np.arange(24).reshape(3, 4, 2)
print(a)
print('after transpose(a):\n', np.transpose(a))
print('original: {} , after transpose(a).shape:{}\t'.format(a.shape, np.transpose(a).shape))
print('\n============================================================================================')

# .T 类似于transpose
print('a.T:\n', a.T)
print('\n============================================================================================')

# rollaxis 函数向后滚动特定的轴到一个特定位置
# arr：数组
# axis：要向后滚动的轴，其它轴的相对位置不会改变
# start：默认为零，表示完整的滚动。会滚动到特定位置。
a = np.arange(12).reshape(2, 2, 3)
print(a)
print(np.where(a==6))
print(a[1, 0, 0])
b = np.rollaxis(a, 2, 0) # 将轴 2 滚动到轴 0（宽度到深度）
print(b)
print(np.where(b==6))
c = np.rollaxis(a, 2, 1) # 将轴 2 滚动到轴 1：（宽度到高度）
print(c)
print(np.where(c==6))
print('\n============================================================================================')

# swapaxes
a = np.arange(8).reshape(2, 2, 2)
print(a)
print('swap后：\n', np.swapaxes(a, 2, 0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3 4 5]
[6 7 8]
0
1
2
3
4
5
6
7
8

[[0 1 2 3]
 [4 5 6 7]]
a.flatten展开: [0 1 2 3 4 5 6 7]
a.flatten以F顺序展开： [0 4 1 5 2 6 3 7]
返回的是拷贝，所以不会改变原始数组:
 [[0 1 2 3]
 [4 5 6 7]]

[[0 1 2 3]
 [4 5 6 7]]
a.reval展开，默认C顺序： [0 1 2 3 4 5 6 7]
a.reval以F顺序展开： [0 4 1 5 2 6 3 7]
返回的是视图，所以会导致原始数组改变:
 [[-1  1  2  3]
 [ 4  5  6  7]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
after transpose(a):
 [[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]
original: (3, 4, 2) , after transpose(a).shape:(2, 4, 3)	

a.T:
 [[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))
6
[[[ 0  3]
  [ 6  9]]

 [[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8

In [22]:
# 位运算 https://www.runoob.com/numpy/numpy-binary-operators.html
# bitwise_and	对数组元素执行 位与 操作
# bitwise_or	对数组元素执行 位或 操作
# invert	按位 取反
# left_shift	向左移动二进制表示的位
# right_shift	向右移动二进制表示的位
a, b = 13, 17
print('13和17对应的二进制为：', bin(a), bin(b))
print('13和17按照位与计算：', np.bitwise_and(13, 17))
print('13和17按照位或计算：', np.bitwise_or(13, 17))
print('\n============================================================================================')

print('13的二进制：', np.binary_repr(13, width=8))
print('13的位反转：', np.invert(np.array([13], dtype=np.uint8)))
print('242的二进制：', np.binary_repr(242, width=8))
print('\n============================================================================================')

print('10的二进制', np.binary_repr(10, width=8))
print('10左移两位：', np.left_shift(10, 2))
print('40的二进制：', np.binary_repr(40, width=8))
print('\n============================================================================================')

print('40右移两位：', np.right_shift(40, 2))

13和17对应的二进制为： 0b1101 0b10001
13和17按照位与计算： 1
13和17按照位或计算： 29

13的二进制： 00001101
13的位反转： [242]
242的二进制： 11110010

10的二进制 00001010
10左移两位： 40
40的二进制： 00101000

40右移两位： 10


In [ ]:
# 字符串函数 https://www.runoob.com/numpy/numpy-string-functions.html
'''
add()	对两个数组的逐个字符串元素进行连接
multiply()	返回按元素多重连接后的字符串
center()	居中字符串
capitalize()	将字符串第一个字母转换为大写
title()	将字符串的每个单词的第一个字母转换为大写
lower()	数组元素转换为小写
upper()	数组元素转换为大写
split()	指定分隔符对字符串进行分割，并返回数组列表
splitlines()	返回元素中的行列表，以换行符分割
strip()	移除元素开头或者结尾处的特定字符
join()	通过指定分隔符来连接数组中的元素
replace()	使用新字符串替换字符串中的所有子字符串
decode()	数组元素依次调用str.decode
encode()	数组元素依次调用str.encode
'''
